import { PRODUCT_NAME } from "@/lib/config";

export const landingCopy = {
  en: {
    title: "A little reassurance.",
    titleAccent: "Every step of the way.",
    description: `${PRODUCT_NAME} is your calm pregnancy companion. Follow your baby's growth and keep your daily care close.`,
    invitation: "Be first to know when we're ready.",
    name: "Your name",
    namePlaceholder: "What should we call you?",
    invalidName: "Please enter your name.",
    email: "Your email address",
    placeholder: "you@example.com",
    join: "Join the waitlist",
    joining: "Joining…",
    note: "One little email when we launch.",
    consent: "By joining, you agree to receive our launch email.",
    invalid: "Please enter a valid email address.",
    unavailable: "We couldn't save your place. Please try again shortly.",
    successTitle: "There's a place for you here.",
    success: "You're on the list. We'll email you when we're ready.",
    footer: "Made with care. For the journey ahead.",
    place: "Growing with you, in India.",
    featureBaby: "Your baby's growth",
    featureCare: "Your daily care",
    featurePeace: "A calmer pregnancy",
  },
  hi: {
    title: "थोड़ा सुकून।",
    titleAccent: "हर कदम पर आपके साथ।",
    description: `${PRODUCT_NAME}, प्रेग्नेंसी में आपका साथी। आपके शिशु का विकास, आपकी रोज़ की देखभाल और मन को थोड़ा सुकून।`,
    invitation: "कुछ प्यारा आने वाला है। सबसे पहले जानें।",
    name: "आपका नाम",
    namePlaceholder: "हम आपको क्या कहकर बुलाएँ?",
    invalidName: "कृपया अपना नाम लिखें।",
    email: "आपका ईमेल पता",
    placeholder: "you@example.com",
    join: "वेटलिस्ट में जुड़ें",
    joining: "जोड़ रहे हैं…",
    note: "जब हम तैयार होंगे, आपको एक ईमेल भेजेंगे।",
    consent: "जुड़कर आप हमारे लॉन्च का ईमेल पाने की सहमति देते हैं।",
    invalid: "कृपया सही ईमेल पता लिखें।",
    unavailable: "अभी आपका नाम नहीं जुड़ पाया। थोड़ी देर में फिर कोशिश करें।",
    successTitle: "आपके लिए एक जगह है।",
    success: "आपका नाम जुड़ गया है। तैयार होते ही हम ईमेल करेंगे।",
    footer: "इस सफ़र के लिए, प्यार से बनाया।",
    place: "भारत में, आपके साथ बढ़ते हुए।",
    featureBaby: "शिशु का विकास",
    featureCare: "रोज़ की देखभाल",
    featurePeace: "प्रेग्नेंसी में सुकून",
  },
} as const;
